### ISSUE TITLE
Example sketches do not compile using ESP8266

### ISSUE THREAD

**Issue by Gianbacchio** [adafruit/Adafruit_ILI9340#12]
Hello,
I'm trying to use your library with a ESP8266 and and the LCD display.
Unfortunately the Arduino IDE cannot compile the software.
Note that:
- I have downloaded your library and correctly installed into Arduino libraries
- I use last Arduino release 1.6.5 updated with ESP8266 modules
- if I set the IDE for Arduino UNO or any other, the compilation is fine.

Sure I'm missing something, but I cannot see. Can you help me? thank you.

the error coming is:
Arduino:1.6.5 (Windows 7), Scheda:"NodeMCU (ESP8266 ESP-12 Module), 80 MHz, 115200"

C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In constructor 'Adafruit_ILI9340::Adafruit_ILI9340(uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:49:3: error: '_cs' was not declared in this scope
   _cs   = cs;
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:50:3: error: '_dc' was not declared in this scope
   _dc   = dc;
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:51:3: error: '_mosi' was not declared in this scope
   _mosi  = mosi;
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:52:3: error: '_miso' was not declared in this scope
   _miso = miso;
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:53:3: error: '_sclk' was not declared in this scope
   _sclk = sclk;
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:54:3: error: '_rst' was not declared in this scope
   _rst  = rst;
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In constructor 'Adafruit_ILI9340::Adafruit_ILI9340(uint8_t, uint8_t, uint8_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:62:3: error: '_cs' was not declared in this scope
   _cs   = cs;
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:63:3: error: '_dc' was not declared in this scope
   _dc   = dc;
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:64:3: error: '_rst' was not declared in this scope
   _rst  = rst;
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:66:3: error: '_mosi' was not declared in this scope
   _mosi  = _sclk = 0;
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:66:12: error: '_sclk' was not declared in this scope
   _mosi  = _sclk = 0;
            ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'void Adafruit_ILI9340::spiwrite(uint8_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:86:17: error: 'mosiport' was not declared in this scope
         SET_BIT(mosiport, mosipinmask);
                 ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:86:27: error: 'mosipinmask' was not declared in this scope
         SET_BIT(mosiport, mosipinmask);
                           ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:86:38: error: 'SET_BIT' was not declared in this scope
         SET_BIT(mosiport, mosipinmask);
                                      ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:89:19: error: 'mosiport' was not declared in this scope
         CLEAR_BIT(mosiport, mosipinmask);
                   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:89:29: error: 'mosipinmask' was not declared in this scope
         CLEAR_BIT(mosiport, mosipinmask);
                             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:89:40: error: 'CLEAR_BIT' was not declared in this scope
         CLEAR_BIT(mosiport, mosipinmask);
                                        ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:92:15: error: 'clkport' was not declared in this scope
       SET_BIT(clkport, clkpinmask);
               ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:92:24: error: 'clkpinmask' was not declared in this scope
       SET_BIT(clkport, clkpinmask);
                        ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:92:34: error: 'SET_BIT' was not declared in this scope
       SET_BIT(clkport, clkpinmask);
                                  ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:94:36: error: 'CLEAR_BIT' was not declared in this scope
       CLEAR_BIT(clkport, clkpinmask);
                                    ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'void Adafruit_ILI9340::writecommand(uint8_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:101:13: error: 'dcport' was not declared in this scope
   CLEAR_BIT(dcport, dcpinmask);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:101:21: error: 'dcpinmask' was not declared in this scope
   CLEAR_BIT(dcport, dcpinmask);
                     ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:101:30: error: 'CLEAR_BIT' was not declared in this scope
   CLEAR_BIT(dcport, dcpinmask);
                              ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:103:13: error: 'clkport' was not declared in this scope
   CLEAR_BIT(clkport, clkpinmask);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:103:22: error: 'clkpinmask' was not declared in this scope
   CLEAR_BIT(clkport, clkpinmask);
                      ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:105:13: error: 'csport' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:105:21: error: 'cspinmask' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                     ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:110:28: error: 'SET_BIT' was not declared in this scope
   SET_BIT(csport, cspinmask);
                            ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'void Adafruit_ILI9340::writedata(uint8_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:116:11: error: 'dcport' was not declared in this scope
   SET_BIT(dcport,  dcpinmask);
           ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:116:20: error: 'dcpinmask' was not declared in this scope
   SET_BIT(dcport,  dcpinmask);
                    ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:116:29: error: 'SET_BIT' was not declared in this scope
   SET_BIT(dcport,  dcpinmask);
                             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:118:13: error: 'clkport' was not declared in this scope
   CLEAR_BIT(clkport, clkpinmask);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:118:22: error: 'clkpinmask' was not declared in this scope
   CLEAR_BIT(clkport, clkpinmask);
                      ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:118:32: error: 'CLEAR_BIT' was not declared in this scope
   CLEAR_BIT(clkport, clkpinmask);
                                ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:120:13: error: 'csport' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:120:21: error: 'cspinmask' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                     ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'void Adafruit_ILI9340::begin()':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:163:11: error: '_rst' was not declared in this scope
   pinMode(_rst, OUTPUT);
           ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:165:11: error: '_dc' was not declared in this scope
   pinMode(_dc, OUTPUT);
           ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:166:11: error: '_cs' was not declared in this scope
   pinMode(_cs, OUTPUT);
           ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:182:3: error: 'cspinmask' was not declared in this scope
   cspinmask = digitalPinToBitMask(_cs);
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:183:3: error: 'dcpinmask' was not declared in this scope
   dcpinmask = digitalPinToBitMask(_dc);
   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:196:13: error: '_sclk' was not declared in this scope
     pinMode(_sclk, OUTPUT);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:197:13: error: '_mosi' was not declared in this scope
     pinMode(_mosi, OUTPUT);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:198:13: error: '_miso' was not declared in this scope
     pinMode(_miso, INPUT);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:207:5: error: 'clkpinmask' was not declared in this scope
     clkpinmask  = digitalPinToBitMask(_sclk);
     ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:208:5: error: 'mosipinmask' was not declared in this scope
     mosipinmask = digitalPinToBitMask(_mosi);
     ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:209:15: error: 'clkport' was not declared in this scope
     CLEAR_BIT(clkport, clkpinmask);
               ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:209:34: error: 'CLEAR_BIT' was not declared in this scope
     CLEAR_BIT(clkport, clkpinmask);
                                  ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:210:15: error: 'mosiport' was not declared in this scope
     CLEAR_BIT(mosiport, mosipinmask);
               ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'void Adafruit_ILI9340::pushColor(uint16_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:367:11: error: 'dcport' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
           ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:367:19: error: 'dcpinmask' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
                   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:367:28: error: 'SET_BIT' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
                            ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:369:13: error: 'csport' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:369:21: error: 'cspinmask' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                     ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:369:30: error: 'CLEAR_BIT' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                              ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'virtual void Adafruit_ILI9340::drawPixel(int16_t, int16_t, uint16_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:385:11: error: 'dcport' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
           ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:385:19: error: 'dcpinmask' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
                   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:385:28: error: 'SET_BIT' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
                            ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:387:13: error: 'csport' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:387:21: error: 'cspinmask' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                     ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:387:30: error: 'CLEAR_BIT' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                              ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'virtual void Adafruit_ILI9340::drawFastVLine(int16_t, int16_t, int16_t, uint16_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:410:11: error: 'dcport' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
           ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:410:19: error: 'dcpinmask' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
                   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:410:28: error: 'SET_BIT' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
                            ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:412:13: error: 'csport' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:412:21: error: 'cspinmask' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                     ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:412:30: error: 'CLEAR_BIT' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                              ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'virtual void Adafruit_ILI9340::drawFastHLine(int16_t, int16_t, int16_t, uint16_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:433:11: error: 'dcport' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
           ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:433:19: error: 'dcpinmask' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
                   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:433:28: error: 'SET_BIT' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
                            ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:434:13: error: 'csport' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:434:21: error: 'cspinmask' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                     ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:434:30: error: 'CLEAR_BIT' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                              ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'virtual void Adafruit_ILI9340::fillRect(int16_t, int16_t, int16_t, int16_t, uint16_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:462:11: error: 'dcport' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
           ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:462:19: error: 'dcpinmask' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
                   ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:462:28: error: 'SET_BIT' was not declared in this scope
   SET_BIT(dcport, dcpinmask);
                            ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:464:13: error: 'csport' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
             ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:464:21: error: 'cspinmask' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                     ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:464:30: error: 'CLEAR_BIT' was not declared in this scope
   CLEAR_BIT(csport, cspinmask);
                              ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'uint8_t Adafruit_ILI9340::spiread()':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:536:20: error: '_sclk' was not declared in this scope
       digitalWrite(_sclk, LOW);
                    ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:539:23: error: '_miso' was not declared in this scope
       if (digitalRead(_miso))
                       ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'uint8_t Adafruit_ILI9340::readdata()':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:549:17: error: '_dc' was not declared in this scope
    digitalWrite(_dc, HIGH);
                 ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:550:17: error: '_cs' was not declared in this scope
    digitalWrite(_cs, LOW);
                 ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp: In member function 'uint8_t Adafruit_ILI9340::readcommand8(uint8_t)':
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:559:17: error: '_dc' was not declared in this scope
    digitalWrite(_dc, LOW);
                 ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:560:17: error: '_sclk' was not declared in this scope
    digitalWrite(_sclk, LOW);
                 ^
C:\Users\Davide\Documents\Arduino\libraries\Adafruit_ILI9340-master\Adafruit_ILI9340.cpp:561:17: error: '_cs' was not declared in this scope
    digitalWrite(_cs, LOW);
                 ^
Errore durante la compilazione

**Comment by glennirwin** [comment]
I discovered the same problems when I tried this library.  With a few changes, I was able to get the graphicsTest to work with a NodeMCU v0.9 using this library. (I also had to use the staging version of the ESP8266 board libraries)  

If you want the changes, I created a fork to save and share the changes at https://github.com/glennirwin/Adafruit_ILI9340

**Comment by Gianbacchio** [comment]
Thank you Glenn for your reply!
I'll follow your changes as soon as possible to have finally the LCD display working with ESP8266
:-))

**Comment by ladyada** [comment]
this library is deprecated, you can use Adafruit_ILI9341 instead!
